name: Sample Tests
on:
  push:
    paths-ignore:
      - "docs/**"
      - "release/**"
      - "deployments/**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "release/**"
      - "deployments/**"
  workflow_dispatch:

jobs:
  tests:
    name: Sample Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.HELPER_APP_ID }}
          private-key: ${{ secrets.HELPER_APP_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'
      - name: Build
        run: go build -o bin/nmath
        shell: bash
      - name: Test
        run: bin/nmath > test.log
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4  
        with:
          name: test.log
          path: test.log
          compression-level: 0
